"""Test fixtures.

Pure-math tests need nothing (they don't request the ``db`` fixture). DB/API
tests run against a dedicated Postgres database (``portfolio_test``) with the
schema generated by Tortoise (not Aerich).

Tortoise/asyncpg connections are bound to the event loop they're created on, so
the DB fixture is **function-scoped** — each test initializes Tortoise on its
own loop, truncates, and tears down. The FastAPI app is driven via httpx's ASGI
transport (no lifespan), reusing that connection.
"""

from __future__ import annotations

import os

import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from tortoise import Tortoise

TEST_DB_URL = os.environ.get(
    "TEST_DATABASE_URL",
    "postgres://portfolio:portfolio@localhost:5432/portfolio_test",
)

TEST_ORM = {
    "connections": {"default": TEST_DB_URL},
    "apps": {"models": {"models": ["app.models"], "default_connection": "default"}},
    "use_tz": True,
    "timezone": "UTC",
}

_TABLES = [
    "asset_quotes",
    "price_bars",
    "asset_fundamentals",
    "fx_rates",
    "portfolio_snapshots",
    "transactions",
    "positions",
    "portfolios",
    "assets",
    "users",
]


@pytest_asyncio.fixture
async def db():
    await Tortoise.init(config=TEST_ORM)
    await Tortoise.generate_schemas(safe=True)
    conn = Tortoise.get_connection("default")
    await conn.execute_query(
        "TRUNCATE " + ", ".join(f'"{t}"' for t in _TABLES) + " RESTART IDENTITY CASCADE"
    )
    try:
        yield
    finally:
        await Tortoise.close_connections()


@pytest_asyncio.fixture
async def client(db):
    from app.main import app

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


@pytest_asyncio.fixture
async def auth_client(client):
    """Authenticated client (registered + logged-in user)."""
    await client.post(
        "/auth/register", json={"email": "t@example.com", "password": "password123"}
    )
    resp = await client.post(
        "/auth/login", data={"username": "t@example.com", "password": "password123"}
    )
    token = resp.json()["access_token"]
    client.headers["Authorization"] = f"Bearer {token}"
    return client
